### BEGIN dsdeploy
# Provides:          portainer
# Required-Start:
# Short-Description: Control pannel for Docker & Docker Swarm
# Description:       Add a better description here
# VAR   "FQDN"
# DEPLOY        "simple", "remote"
### END dsdeploy

version: '3.4'

services:
  portainer:
    image: portainer/portainer
    command: '-H "tcp://tasks.agent:9001" --tlsskipverify'
    ports:
      - ${PUBLIC_PORT}:9000
    networks:
      - proxy
      - portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
     #- ${REMOTE_MOUNT}/${STACK_NAME}/portainer/data:/data
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: 9000
        #traefik.frontend.rule: "Host:portainer.34.77.5.19.nip.io,portainer.35.195.212.147.nip.io,portainer.34.77.228.172.nip.io"
        traefik.frontend.rule: "Host:portainer.${IP1}.nip.io,portainer.${IP2}.nip.io,portainer.${IP3}.nip.io"
        traefik.docker.network: 'proxy'
      placement:
        constraints: [node.role == manager]
    
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

volumes:
  portainer:
    driver_opts:
      type: "nfs"
      o: "addr=master01,nolock,soft,rw"
      device: ":/srv/nfs/portainer"

networks:
  portainer_agent:
    external: true
  proxy:
    external: true
